-- Reminders. Run this once in your Supabase SQL editor, the same way sync.sql
-- and push.sql were run. Safe to re-run: every statement is if-not-exists or a
-- drop-then-create.
--
-- WHY IT IS A TABLE AND NOT JUST THE TILE'S OWN SLOT. Every other tile keeps
-- its state in one JSON slot and that is enough, because nothing but the tile
-- ever reads it. A reminder is different: the thing that has to read it is a
-- cron job running at 07:00 while the phone is face down on a table. It cannot
-- open the app to find out what you wanted. So the RULE has to live somewhere
-- the server can query, in columns, and that is this.
--
-- IT REUSES THE PUSH PLUMBING THAT ALREADY EXISTS. push_subscriptions, the
-- VAPID keys and sw.js were all built for the rest timer (supabase/push.sql).
-- One permission, one subscription, one service worker. This adds the rules
-- and its own sender, and touches none of that.

-- 1. THE RULES. One row per reminder.
--
--    THE PRIMARY KEY IS (user_id, id) AND id IS THE TILE'S OWN STRING. The
--    tile is the source of truth for the list - it writes, the server only
--    reads and fires - so the id it already uses in its own vault slot is the
--    id here. A uuid generated by the database would mean the tile could not
--    name its own row on the next sync, and two people's boards must never be
--    able to collide on 'r17' either, hence the pair.
create table if not exists reminders (
  user_id    uuid not null references auth.users on delete cascade,
  id         text not null,
  title      text not null,
  body       text,

  -- 'HH:MM', and it is LOCAL TO tz, never UTC. This is the whole reason the
  -- rule is stored rather than an absolute instant: 07:00 means 07:00 on the
  -- clock in the room, in March and in November, and an absolute timestamp
  -- would drift an hour twice a year and be wrong in a different country.
  at_time    text not null,
  tz         text not null default 'UTC',

  -- once | daily | weekdays | weekends | days
  repeat     text not null default 'once',
  -- Only read when repeat = 'days'. 0 is Sunday, 6 is Saturday, matching
  -- JavaScript's getDay() and the tile's own chips.
  days       smallint[] not null default '{}',
  -- Only read when repeat = 'once'. A local date, 'YYYY-MM-DD'.
  on_date    date,

  enabled    boolean not null default true,
  -- Keeps the notification on screen until it is tapped, instead of it sliding
  -- away on its own. Android honours it. iOS largely does not, and the tile
  -- says so rather than promising something the phone will not do.
  sticky     boolean not null default false,

  -- THE DOUBLE-SEND GUARD, and it is a KEY rather than a date on purpose:
  -- 'YYYY-MM-DD@HH:MM', the local day plus the time it fired for.
  --
  -- A plain date would have been a bug the day you moved a reminder. Fire the
  -- 07:00 one, then change it to 22:00 that afternoon: with a date, today is
  -- already marked done and the 22:00 never comes. Because the time is part of
  -- the key, changing the time changes the key, and the new occurrence is
  -- simply one this reminder has not fired yet. No migration, no clearing, no
  -- second column that can disagree with the first.
  last_fired_key text,

  -- What stops a reminder you set at 08:00 for 07:30 going off immediately.
  -- The sender only fires an occurrence that came AFTER the rule was written.
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  primary key (user_id, id)
);

alter table reminders enable row level security;

drop policy if exists "own reminders" on reminders;
create policy "own reminders" on reminders
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- RLS never even evaluates without the grant. Same law as sync.sql.
grant select, insert, update, delete on reminders to authenticated;

-- The sender's only query: every enabled reminder, every tick. Partial, because
-- a switched-off reminder is never read and there is no reason to walk it.
create index if not exists reminders_enabled on reminders (user_id) where enabled;

-- THERE IS DELIBERATELY NO PRUNE FUNCTION HERE, unlike push.sql.
--
-- A rest timer is machine exhaust: it is written by the app, means nothing an
-- hour later, and would pile up forever unwatched. A reminder is something a
-- person sat down and typed. Deleting it on a schedule would be this board
-- throwing away his work quietly, which is the one thing it is not allowed to
-- do. A one-off that has fired switches itself off and stays in the list,
-- visible, until he removes it himself.


-- ---------------------------------------------------------------------------
-- 2. THE SCHEDULE. Run this AFTER deploying the send-reminder-push function,
--    or the first tick calls a URL that does not exist yet.
--
--    Replace <PROJECT-REF> with zqqqczmqkacigihzdmbs and <SERVICE-ROLE-KEY>
--    with the service_role key from Settings -> API. That key bypasses RLS on
--    purpose: cron is not a signed-in user, and it has to read reminders
--    across every device that subscribed.
--
--    EVERY MINUTE, not every fifteen seconds like the rest timer. A rest timer
--    that is a minute late is useless; a reminder that is a minute late is a
--    reminder. Four times fewer calls for no loss.
-- ---------------------------------------------------------------------------

-- create extension if not exists pg_cron;
-- create extension if not exists pg_net;
--
-- select cron.schedule(
--   'send-reminder-push',
--   '* * * * *',
--   $$
--   select net.http_post(
--     url     := 'https://<PROJECT-REF>.supabase.co/functions/v1/send-reminder-push',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer <SERVICE-ROLE-KEY>'
--     ),
--     body    := '{}'::jsonb
--   );
--   $$
-- );

-- To stop it later:
--   select cron.unschedule('send-reminder-push');
--
-- To see whether it is running:
--   select * from cron.job;
--   select * from cron.job_run_details where jobname = 'send-reminder-push'
--     order by start_time desc limit 20;
